branches/feature/auguste-implement-parameters/ (augusteuzuotaite@Augustes-MacBook-Air.local) Added severity levels of error messages.
git-svn-id: svn://saulius-grazulis.lt/bibliophile/branches/feature@29 63c7f2d9-9d11-409a-a4db-444dd1c7f1db

diff --git a/auguste-implement-parameters/europepmc-xml b/auguste-implement-parameters/europepmc-xml
--- a/auguste-implement-parameters/europepmc-xml
+++ b/auguste-implement-parameters/europepmc-xml
@@ -47,15 +47,15 @@ do
 	        exit
 	        ;;
         --options|--option)
-            echo "$0: '--options' is a place-holder; " 
-                 "please use '$0 --help' to get the list of available options."
-            exit 2
+            echo "$0: WARNING, '--options' is a place-holder; " \
+                "please use '$0 --help' to get the list of available options." \
+                >&2
             ;;
         --search-term|--search)
             SEARCH_TERM="$2"
             shift 
             ;;
-        -*) echo "$0: unknown option '$1'" >&2 ; exit 1 ;;
+        -*) echo "$0: ERROR, unknown option '$1'" >&2 ; exit 1 ;;
         *)  FILES="${FILES} '$1'" ;;
     esac
     shift
@@ -103,8 +103,8 @@ do
 
     j=$(expr $n / $pageSize)
 
-    echo n=$n
-    echo j=$j
+    echo $0: NOTE, number of records found = $n  >&2 
+    echo $0: NOTE, number of pages = $j >&2
     if [ $(expr $n % $pageSize) -ne 0 ]
     then
         j=$(expr $j + 1 )
@@ -119,7 +119,7 @@ do
         cursorMark=$(echo "$xmlresult" \
             | perl -077 -ne \
                 'print $1 if /<nextCursorMark>(.*?)<\/nextCursorMark>/ms')
-        echo i=$i
+        echo $0: NOTE, page $i downloaded >&2 
     done
 
 done
